version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: ./infra/db/Dockerfile
    image: ganntt-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
  app:
    build:
      context: ./backend
      dockerfile: ./../infra/rails/Dockerfile
    image: ganntt-rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    volumes:
      - ./backend/:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  web:
    build:
      context: ./frontend
      dockerfile: ./../infra/nuxt/Dockerfile
    image: ganntt-nuxt
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - "./frontend:/frontend"
      - node_modules_volume:/front/node_modules
    tty: true
    environment:
    - HOST=0.0.0.0
    - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
  db-data: